# Generated by Django 4.1.3 on 2023-07-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='icon',
        ),
    ]
